run_name = "______"
qk = [ 20, 20, 20, 20, 10, 10, 10,]
h_b = [ 1100, 1700, 1800, 1900, 3300, 3300, 3300,]
seed = 20
reduced = true
h_t_40 = 200000
h_t_20 = 140000
handling_time = 0.16666666666666666
C_range = [ 100, 150,]
N_range = [ 5, 5,]
Oc_range = [ 24, 190,]
Oc_offset_range = [ 110, 350,]
travel_time_long_range = [ 60, 100,]
travel_angle = 3.141592653589793
P40_range = [ 0.2, 0.22,]
PExport_range = [ 0.05, 0.75,]
C_range_reduced = [ 65, 75,]
N_range_reduced = [ 6, 6,]
gamma = 100
big_m = 1000000
