run_name = "______"
qk = [ 20, 20,]
h_b = [ 1100, 1700,]
seed = 0
reduced = true
h_t_40 = 200000.0
h_t_20 = 140000.0
handling_time = 0.16666666666666666
C_range = [ 150, 175,]
N_range = [ 20, 20,]
Oc_range = [ 0, 48,]
Oc_offset_range = [ 48, 96,]
travel_time_long_range = [ 9, 13,]
travel_angle = 0.39269908169872414
P40_range = [ 0.2, 0.22,]
PExport_range = [ 0.05, 0.75,]
C_range_reduced = [ 5, 10,]
N_range_reduced = [ 4, 4,]
gamma = 100
big_m = 1000
